The system command is coughing up errors, the syntax isn't right for the latest ubuntu/bash install.
[4] pry(main)> g.extend Chess::Gnuchess
sh: 1: Syntax error: Bad fd number
RuntimeError: You need to install Gnuchess to use the module Chess::Gnuchess.

This change fixes that.